### ISSUE TITLE
undefined method zero?' for nil:NilClass while executing check-rabbitmq-queue-drain-time.rb

### ISSUE THREAD

**Issue by infa-kparida** [sensu-plugins/sensu-plugins-rabbitmq#116]
Sometimes We are getting `undefined method` zero?' for nil:NilClass` while executing check-rabbitmq-queue-drain-time.rb check.Below is the complete error snippet

{"timestamp":"2019-03-04T00:51:07.881054+0000","level":"info","message":"publishing check result","payload":{"client":"sensu-redis-rmq-test","check":{"command":"/opt/sensu/embedded/bin/check-rabbitmq-queue-drain-time.rb","standalone":true,"handler":" ","contact":"","playbook":"","interval":60,"name":"checkRMQqueuedraintime","issued":1551660667,"executed":1551660667,"duration":0.205,"output":"Check failed to run: undefined method `zero?' for nil:NilClass, [\"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-rabbitmq-6.0.0/bin/check-rabbitmq-queue-drain-time.rb:129:in `block in run'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-rabbitmq-6.0.0/bin/check-rabbitmq-queue-drain-time.rb:127:in `each'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-rabbitmq-6.0.0/bin/check-rabbitmq-queue-drain-time.rb:127:in `run'\", \"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.7.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'\"]\n","status":3}}

**Comment by infa-kparida** [comment]
@majormoses  Any progress on this ?

**Comment by majormoses** [comment]
No I have not had the time to look, I do not work for sensu and donate time to the community when I have it. If you need immediate support please reach out to support@sensu.io where they are bound by SLA for enterprise customers per your support plan.I may have some time over the weekend to start taking a look but no promises.

**Comment by zenmetsu** [comment]
This was marked as Fixed, but the issue still comes up with the 8.1.0 release of this plugin.  The other checks are fine, but the drain-time check fails periodically with this error, so I am assuming that when the queue is empty or nil is returned, it is still triggering the error that the OP reported.
