### ISSUE TITLE
check-rabbitmq-queue-drain-time.rb fails "no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-rabbitmq#31]
I got this error:

```
Check failed to run: no implicit conversion of nil into String, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:96:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:96:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:96:in `block in acquire_rabbitmq_queues'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:96:in `select'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:96:in `acquire_rabbitmq_queues'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rabbitmq-1.2.0/bin/check-rabbitmq-queue-drain-time.rb:109:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by envintus** [comment]
I'm experiencing the same issue as well.

**Comment by majormoses** [comment]
looks like this has been merged is there a reason this is still open?

**Comment by envintus** [comment]
No reason. Forgot this was open. Thanks!
