### ISSUE TITLE
404 error after upgrading to RabbitMQ 3.6.9

### ISSUE THREAD

**Issue by bootswithdefer** [sensu-plugins/sensu-plugins-rabbitmq#57]
After upgrading to RabbitMQ 3.6.9 (from 3.6.6) I get the following error from the queue check:
`check-rabbitmq-queue.rb -u monitoring --password monitoring -w 5000 -c 10000 --queue results,keepalives`

```
Check failed to run: 404 "Not Found", 
["/opt/sensu/embedded/lib/ruby/2.4.0/net/http/response.rb:122:in `error!'", 
"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:59:in `fetch_uri'", 
"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:24:in `query_api'", 
"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:28:in `method_missing'", 
"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-rabbitmq-2.1.0/bin/check-rabbitmq-queue.rb:118:in `run'", 
"/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

**Comment by bootswithdefer** [comment]
It appears RabbitMQ has tightened up it's URI handling.  The method_missing call in the plugin is adding an extra slash which worked on the old version but not on the new one.

RabbitMQ 3.6.9
```
curl -I http://monitoring:monitoring@localhost:15672/api//queues/
HTTP/1.1 404 Not Found
server: Cowboy
date: Tue, 11 Apr 2017 15:18:01 GMT
content-length: 49
content-type: application/json
```
RabbitMQ 3.6.6:
```
curl -I http://monitoring:monitoring@localhost:15672/api/queues//
HTTP/1.1 200 OK
vary: Accept-Encoding, origin
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 11 Apr 2017 15:18:04 GMT
Content-Type: application/json
Content-Length: 769127
Cache-Control: no-cache
```

**Comment by majormoses** [comment]
looks like this was merged but never released. please ping me if I do not release in the next 24 hours.

**Comment by majormoses** [comment]
this should be included by this release: https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/2.3.0
